# Generated by Django 3.1.1 on 2020-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='company_address',
            field=models.CharField(default='岩本町', max_length=200, verbose_name='場所'),
        ),
        migrations.AddField(
            model_name='projects',
            name='company_name',
            field=models.CharField(default='pcn', max_length=50, verbose_name='会社名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='job_detail',
            field=models.CharField(default='mysql', max_length=300, verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='needed_member',
            field=models.CharField(default='2', max_length=10, verbose_name='人数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='needed_skill',
            field=models.CharField(default='java', max_length=200, verbose_name='必須スキル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='other_skill',
            field=models.CharField(default='python', max_length=200, verbose_name='追加スキル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='period',
            field=models.CharField(default='3months', max_length=50, verbose_name='期間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='project_name',
            field=models.CharField(default='AAA', max_length=300, verbose_name='案件名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='sales_rep',
            field=models.CharField(default='uno', max_length=20, verbose_name='担当者名'),
            preserve_default=False,
        ),
    ]
